---
title: "Minimal Hardware Estimates"
subtitle: "How low you can go?"
author: "Alexander Minyushkin"
date: 2019-08-16T19:00:00+03:00
categories: ["GCP"]
tags: ["Cloud", "GCP", "Hardware"]

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
oldw <- getOption("warn")
options(warn = -1)

usePackage <- function(p) {
  if (!is.element(p, installed.packages()[,1]))
    install.packages(p, dep = TRUE)
  require(p, character.only = TRUE, quietly = TRUE)
}

usePackage("data.table") # for fast merging of access log & sar
usePackage("parallel")
usePackage("plyr")
usePackage("ggplot2")

usePackage('DT')
usePackage("plotly")
usePackage("jsonlite")
usePackage("htmltools")

Sys.setlocale("LC_TIME", "us")

options(stringsAsFactors = FALSE)


```

### Problem
When you want to estimate hardware for Non-production environment you want to spend minimal resources on it.

Especially if you need it only for development where very low workloads expected.

[Googling](https://www.google.com/search?q=kafka+minimum+requirements) minimal hardware recommendations may disappoint you, because authors avoid to give such recommendations.

For example Kafka: [We are using dual quad-core Intel Xeon machines with 24GB of memory.](https://kafka.apache.org/documentation/#hwandos) 24 GB RAM, are you sure?

Most popular answer is on Quora: [Do not cheap out and try to have a machine with 48TB disk and 2GB ram and a duel core CPU, but dont go crazy.](https://www.quora.com/What-is-viable-hardware-for-Zookeeper-and-Kafka-brokers)


Here is Liferay: [For the purposes of this document we will use a **very simple** reference hardware configuration
illustrated here:](https://www.liferay.com/documents/10182/1645493/Liferay+Portal+EE+Reference+Architecture+%26+Hardware+Requirements/7f618f87-ca55-4e39-ba21-b3faadbca206?version=1.3)

1. Web Server
 + 1 x Intel Core 2 Duo E6405 2.13GHz CPU, 2MB L2 cache (2 cores total)
 + 4GB memory
 + 1 x 146GB 7.2k RPM IDE
2. Application Server
 + 2 x Intel Core 2 Quad E5430 2.66GHz CPU, 12MB L2 cache (8 cores total)
 + 8GB memory
 + 2 x 146GB 10k RPM SCSI
3. Database Tier
 + 1 x Intel Core 2 Quad E5430 2.66GHz CPU, 12MB L2 cache (8 cores total)
 + 16GB memory
 + 4 x 146GB 15k RPM SCSI


It all looks too big for non-prod environment with near zero workload. 

### Solution
To solve this problem I found it useful to take a look at GCP marketplace.

[GCP Marketplace Kafka](https://console.cloud.google.com/marketplace/details/bitnami-launchpad/kafka)

+ VM instance: 1 vCPU + 3.75 GB memory (n1-standard-1)
+ Standard persistent disk: 10 GB

[GCP Marketplace Liferay](https://console.cloud.google.com/marketplace/details/bitnami-launchpad/liferay)

+ VM instance: 2 vCPUs + 7.5 GB memory (n1-standard-2)
+ Standard persistent disk: 10 GB

Default recommendations there are small enough. You can use them without verification if you trust Google Cloud. 

After all, you can spend one cent, try to deploy on smaller instances and check if it works.

You can leave comments here https://twitter.com/AMiniushkin 

